from typing import NamedTuple


class BoneRule(NamedTuple):
    name: str
    role: str
    regions: frozenset[str]
    side: str | None
    parent: str | None
    tags: frozenset[str]


ROLE_MOTION = "motion"
ROLE_SHAPE = "shape"
ROLE_ASSIST = "assist"
ROLE_ANCHOR = "anchor"
ROLE_OTHER = "other"

REGION_TORSO = "torso"
REGION_ARM = "arm"
REGION_LEG = "leg"
REGION_BREAST = "breast"
REGION_HAND = "hand"
REGION_LOWER_BODY = "lower_body"
REGION_BUTT = "butt"
REGION_NIPPLE = "nipple"
REGION_ROOT = "root"

TRANSFER_REGION_TORSO = "TORSO"
TRANSFER_REGION_ARM = "ARM"
TRANSFER_REGION_LEG = "LEG"

TAG_LOWER_BODY_LIMB = "lower_body_limb"
TAG_LOWER_BODY_WITH_SIRI = "lower_body_with_siri"
TAG_NIPPLE_DETAIL = "nipple_detail"
TAG_BUST_CHAIN = "bust_chain"
TAG_TRANSFER_SAFE_TORSO = "transfer_safe_torso"
TAG_TRANSFER_SAFE_ARM = "transfer_safe_arm"
TAG_TRANSFER_SAFE_LEG = "transfer_safe_leg"
TAG_ROOT_ANCHOR = "root_anchor"


_BONE_RULE_DATA = {'cf_d_ana': {'parent': 'cf_j_waist02',
              'regions': ('lower_body', 'torso'),
              'role': 'assist',
              'side': None,
              'tags': ('lower_body_limb', 'lower_body_with_siri')},
 'cf_d_arm01_L': {'parent': 'cf_j_arm00_L',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_arm01_R': {'parent': 'cf_j_arm00_R',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_arm02_L': {'parent': 'cf_j_arm00_L',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_arm02_R': {'parent': 'cf_j_arm00_R',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_arm03_L': {'parent': 'cf_j_arm00_L',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_arm03_R': {'parent': 'cf_j_arm00_R',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_bnip01_L': {'parent': 'cf_j_bust03_L',
                   'regions': ('breast', 'nipple'),
                   'role': 'assist',
                   'side': 'L',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_d_bnip01_R': {'parent': 'cf_j_bust03_R',
                   'regions': ('breast', 'nipple'),
                   'role': 'assist',
                   'side': 'R',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_d_bust00': {'parent': 'cf_j_spine03',
                 'regions': ('breast',),
                 'role': 'assist',
                 'side': None,
                 'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_bust01_L': {'parent': 'cf_s_bust00_L',
                   'regions': ('breast',),
                   'role': 'assist',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_bust01_R': {'parent': 'cf_s_bust00_R',
                   'regions': ('breast',),
                   'role': 'assist',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_bust02_L': {'parent': 'cf_j_bust01_L',
                   'regions': ('breast',),
                   'role': 'assist',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_bust02_R': {'parent': 'cf_j_bust01_R',
                   'regions': ('breast',),
                   'role': 'assist',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_bust03_L': {'parent': 'cf_j_bust02_L',
                   'regions': ('breast',),
                   'role': 'assist',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_bust03_R': {'parent': 'cf_j_bust02_R',
                   'regions': ('breast',),
                   'role': 'assist',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_d_forearm02_L': {'parent': 'cf_j_forearm01_L',
                      'regions': ('arm',),
                      'role': 'assist',
                      'side': 'L',
                      'tags': ('transfer_safe_arm',)},
 'cf_d_forearm02_R': {'parent': 'cf_j_forearm01_R',
                      'regions': ('arm',),
                      'role': 'assist',
                      'side': 'R',
                      'tags': ('transfer_safe_arm',)},
 'cf_d_hand_L': {'parent': 'cf_s_wrist_L',
                 'regions': ('hand',),
                 'role': 'assist',
                 'side': 'L',
                 'tags': ('transfer_safe_arm',)},
 'cf_d_hand_R': {'parent': 'cf_s_wrist_R',
                 'regions': ('hand',),
                 'role': 'assist',
                 'side': 'R',
                 'tags': ('transfer_safe_arm',)},
 'cf_d_kneeF_L': {'parent': 'cf_j_leg01_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_kneeF_R': {'parent': 'cf_j_leg01_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_kokan': {'parent': 'cf_j_waist02',
                'regions': ('lower_body', 'torso'),
                'role': 'assist',
                'side': None,
                'tags': ('lower_body_limb', 'lower_body_with_siri')},
 'cf_d_leg02_L': {'parent': 'cf_j_leg01_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_leg02_R': {'parent': 'cf_j_leg01_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_leg03_L': {'parent': 'cf_j_leg01_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_leg03_R': {'parent': 'cf_j_leg01_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_shoulder02_L': {'parent': 'cf_j_shoulder_L',
                       'regions': ('arm',),
                       'role': 'assist',
                       'side': 'L',
                       'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_d_shoulder02_R': {'parent': 'cf_j_shoulder_R',
                       'regions': ('arm',),
                       'role': 'assist',
                       'side': 'R',
                       'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_d_shoulder_L': {'parent': 'cf_j_spine03',
                     'regions': ('arm',),
                     'role': 'assist',
                     'side': 'L',
                     'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_d_shoulder_R': {'parent': 'cf_j_spine03',
                     'regions': ('arm',),
                     'role': 'assist',
                     'side': 'R',
                     'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_d_siri01_L': {'parent': 'cf_d_siri_L',
                   'regions': ('butt', 'lower_body'),
                   'role': 'assist',
                   'side': 'L',
                   'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_d_siri01_R': {'parent': 'cf_d_siri_R',
                   'regions': ('butt', 'lower_body'),
                   'role': 'assist',
                   'side': 'R',
                   'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_d_siri_L': {'parent': 'cf_j_waist02',
                 'regions': ('butt', 'lower_body'),
                 'role': 'assist',
                 'side': 'L',
                 'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_d_siri_R': {'parent': 'cf_j_waist02',
                 'regions': ('butt', 'lower_body'),
                 'role': 'assist',
                 'side': 'R',
                 'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_d_thigh01_L': {'parent': 'cf_j_thigh00_L',
                    'regions': ('leg', 'lower_body'),
                    'role': 'assist',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_thigh01_R': {'parent': 'cf_j_thigh00_R',
                    'regions': ('leg', 'lower_body'),
                    'role': 'assist',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_thigh02_L': {'parent': 'cf_j_thigh00_L',
                    'regions': ('leg', 'lower_body'),
                    'role': 'assist',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_thigh02_R': {'parent': 'cf_j_thigh00_R',
                    'regions': ('leg', 'lower_body'),
                    'role': 'assist',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_thigh03_L': {'parent': 'cf_j_thigh00_L',
                    'regions': ('leg', 'lower_body'),
                    'role': 'assist',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_thigh03_R': {'parent': 'cf_j_thigh00_R',
                    'regions': ('leg', 'lower_body'),
                    'role': 'assist',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_d_wrist_L': {'parent': 'cf_j_forearm01_L',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_d_wrist_R': {'parent': 'cf_j_forearm01_R',
                  'regions': ('arm',),
                  'role': 'assist',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_j_ana': {'parent': 'cf_d_ana',
              'regions': ('lower_body', 'torso'),
              'role': 'motion',
              'side': None,
              'tags': ('lower_body_limb', 'lower_body_with_siri')},
 'cf_j_arm00_L': {'parent': 'cf_j_shoulder_L',
                  'regions': ('arm',),
                  'role': 'motion',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_j_arm00_R': {'parent': 'cf_j_shoulder_R',
                  'regions': ('arm',),
                  'role': 'motion',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_j_bnip02_L': {'parent': 'cf_s_bnip02_L',
                   'regions': ('breast', 'nipple'),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_j_bnip02_R': {'parent': 'cf_s_bnip02_R',
                   'regions': ('breast', 'nipple'),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_j_bnip02root_L': {'parent': 'cf_d_bnip01_L',
                       'regions': ('breast', 'nipple'),
                       'role': 'motion',
                       'side': 'L',
                       'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_j_bnip02root_R': {'parent': 'cf_d_bnip01_R',
                       'regions': ('breast', 'nipple'),
                       'role': 'motion',
                       'side': 'R',
                       'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_j_bust01_L': {'parent': 'cf_d_bust01_L',
                   'regions': ('breast',),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_j_bust01_R': {'parent': 'cf_d_bust01_R',
                   'regions': ('breast',),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_j_bust02_L': {'parent': 'cf_d_bust02_L',
                   'regions': ('breast',),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_j_bust02_R': {'parent': 'cf_d_bust02_R',
                   'regions': ('breast',),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_j_bust03_L': {'parent': 'cf_d_bust03_L',
                   'regions': ('breast',),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_j_bust03_R': {'parent': 'cf_d_bust03_R',
                   'regions': ('breast',),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_j_foot_L': {'parent': 'cf_j_leg03_L',
                 'regions': ('leg', 'lower_body'),
                 'role': 'motion',
                 'side': 'L',
                 'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_foot_R': {'parent': 'cf_j_leg03_R',
                 'regions': ('leg', 'lower_body'),
                 'role': 'motion',
                 'side': 'R',
                 'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_forearm01_L': {'parent': 'cf_j_arm00_L',
                      'regions': ('arm',),
                      'role': 'motion',
                      'side': 'L',
                      'tags': ('transfer_safe_arm',)},
 'cf_j_forearm01_R': {'parent': 'cf_j_arm00_R',
                      'regions': ('arm',),
                      'role': 'motion',
                      'side': 'R',
                      'tags': ('transfer_safe_arm',)},
 'cf_j_hand_L': {'parent': 'cf_j_forearm01_L',
                 'regions': ('hand',),
                 'role': 'motion',
                 'side': 'L',
                 'tags': ('transfer_safe_arm',)},
 'cf_j_hand_R': {'parent': 'cf_j_forearm01_R',
                 'regions': ('hand',),
                 'role': 'motion',
                 'side': 'R',
                 'tags': ('transfer_safe_arm',)},
 'cf_j_head': {'parent': 'cf_j_neck',
               'regions': ('torso',),
               'role': 'motion',
               'side': None,
               'tags': ('transfer_safe_torso',)},
 'cf_j_hips': {'parent': 'cf_n_height',
               'regions': ('lower_body', 'torso'),
               'role': 'motion',
               'side': None,
               'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_j_index01_L': {'parent': 'cf_s_hand_L',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_index01_R': {'parent': 'cf_s_hand_R',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_index02_L': {'parent': 'cf_j_index01_L',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_index02_R': {'parent': 'cf_j_index01_R',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_index03_L': {'parent': 'cf_j_index02_L',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_index03_R': {'parent': 'cf_j_index02_R',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_kokan': {'parent': 'cf_d_kokan',
                'regions': ('lower_body', 'torso'),
                'role': 'motion',
                'side': None,
                'tags': ('lower_body_limb', 'lower_body_with_siri')},
 'cf_j_leg01_L': {'parent': 'cf_j_thigh00_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'motion',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_leg01_R': {'parent': 'cf_j_thigh00_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'motion',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_leg03_L': {'parent': 'cf_j_leg01_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'motion',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_leg03_R': {'parent': 'cf_j_leg01_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'motion',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_little01_L': {'parent': 'cf_s_hand_L',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_little01_R': {'parent': 'cf_s_hand_R',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_little02_L': {'parent': 'cf_j_little01_L',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_little02_R': {'parent': 'cf_j_little01_R',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_little03_L': {'parent': 'cf_j_little02_L',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_little03_R': {'parent': 'cf_j_little02_R',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_middle01_L': {'parent': 'cf_s_hand_L',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_middle01_R': {'parent': 'cf_s_hand_R',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_middle02_L': {'parent': 'cf_j_middle01_L',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_middle02_R': {'parent': 'cf_j_middle01_R',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_middle03_L': {'parent': 'cf_j_middle02_L',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_middle03_R': {'parent': 'cf_j_middle02_R',
                     'regions': ('hand',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_j_neck': {'parent': 'cf_j_spine03',
               'regions': ('torso',),
               'role': 'motion',
               'side': None,
               'tags': ('transfer_safe_torso',)},
 'cf_j_ring01_L': {'parent': 'cf_s_hand_L',
                   'regions': ('hand',),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('transfer_safe_arm',)},
 'cf_j_ring01_R': {'parent': 'cf_s_hand_R',
                   'regions': ('hand',),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('transfer_safe_arm',)},
 'cf_j_ring02_L': {'parent': 'cf_j_ring01_L',
                   'regions': ('hand',),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('transfer_safe_arm',)},
 'cf_j_ring02_R': {'parent': 'cf_j_ring01_R',
                   'regions': ('hand',),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('transfer_safe_arm',)},
 'cf_j_ring03_L': {'parent': 'cf_j_ring02_L',
                   'regions': ('hand',),
                   'role': 'motion',
                   'side': 'L',
                   'tags': ('transfer_safe_arm',)},
 'cf_j_ring03_R': {'parent': 'cf_j_ring02_R',
                   'regions': ('hand',),
                   'role': 'motion',
                   'side': 'R',
                   'tags': ('transfer_safe_arm',)},
 'cf_j_root': {'parent': 'p_cf_body_00',
               'regions': ('root',),
               'role': 'motion',
               'side': None,
               'tags': ('root_anchor',)},
 'cf_j_shoulder_L': {'parent': 'cf_d_shoulder_L',
                     'regions': ('arm',),
                     'role': 'motion',
                     'side': 'L',
                     'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_j_shoulder_R': {'parent': 'cf_d_shoulder_R',
                     'regions': ('arm',),
                     'role': 'motion',
                     'side': 'R',
                     'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_j_siri_L': {'parent': 'cf_d_siri01_L',
                 'regions': ('butt', 'lower_body'),
                 'role': 'motion',
                 'side': 'L',
                 'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_j_siri_R': {'parent': 'cf_d_siri01_R',
                 'regions': ('butt', 'lower_body'),
                 'role': 'motion',
                 'side': 'R',
                 'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_j_spine01': {'parent': 'cf_j_hips',
                  'regions': ('torso',),
                  'role': 'motion',
                  'side': None,
                  'tags': ('transfer_safe_torso',)},
 'cf_j_spine02': {'parent': 'cf_j_spine01',
                  'regions': ('torso',),
                  'role': 'motion',
                  'side': None,
                  'tags': ('transfer_safe_torso',)},
 'cf_j_spine03': {'parent': 'cf_j_spine02',
                  'regions': ('torso',),
                  'role': 'motion',
                  'side': None,
                  'tags': ('transfer_safe_torso',)},
 'cf_j_thigh00_L': {'parent': 'cf_j_waist02',
                    'regions': ('leg', 'lower_body'),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_thigh00_R': {'parent': 'cf_j_waist02',
                    'regions': ('leg', 'lower_body'),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_thumb01_L': {'parent': 'cf_s_hand_L',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_thumb01_R': {'parent': 'cf_s_hand_R',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_thumb02_L': {'parent': 'cf_j_thumb01_L',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_thumb02_R': {'parent': 'cf_j_thumb01_R',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_thumb03_L': {'parent': 'cf_j_thumb02_L',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'L',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_thumb03_R': {'parent': 'cf_j_thumb02_R',
                    'regions': ('hand',),
                    'role': 'motion',
                    'side': 'R',
                    'tags': ('transfer_safe_arm',)},
 'cf_j_toes_L': {'parent': 'cf_j_foot_L',
                 'regions': ('leg', 'lower_body'),
                 'role': 'motion',
                 'side': 'L',
                 'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_toes_R': {'parent': 'cf_j_foot_R',
                 'regions': ('leg', 'lower_body'),
                 'role': 'motion',
                 'side': 'R',
                 'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_j_waist01': {'parent': 'cf_j_hips',
                  'regions': ('lower_body', 'torso'),
                  'role': 'motion',
                  'side': None,
                  'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_j_waist02': {'parent': 'cf_j_waist01',
                  'regions': ('lower_body', 'torso'),
                  'role': 'motion',
                  'side': None,
                  'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_n_height': {'parent': 'cf_j_root', 'regions': ('root',), 'role': 'anchor', 'side': None, 'tags': ('root_anchor',)},
 'cf_o_root': {'parent': 'p_cf_body_00',
               'regions': ('root',),
               'role': 'anchor',
               'side': None,
               'tags': ('root_anchor',)},
 'cf_s_ana': {'parent': 'cf_j_ana',
              'regions': ('lower_body', 'torso'),
              'role': 'shape',
              'side': None,
              'tags': ('lower_body_limb', 'lower_body_with_siri')},
 'cf_s_arm01_L': {'parent': 'cf_d_arm01_L',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_arm01_R': {'parent': 'cf_d_arm01_R',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_arm02_L': {'parent': 'cf_d_arm02_L',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_arm02_R': {'parent': 'cf_d_arm02_R',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_arm03_L': {'parent': 'cf_d_arm03_L',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_arm03_R': {'parent': 'cf_d_arm03_R',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_bnip015_L': {'parent': 'cf_d_bnip01_L',
                    'regions': ('breast', 'nipple'),
                    'role': 'shape',
                    'side': 'L',
                    'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip015_R': {'parent': 'cf_d_bnip01_R',
                    'regions': ('breast', 'nipple'),
                    'role': 'shape',
                    'side': 'R',
                    'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip01_L': {'parent': 'cf_d_bnip01_L',
                   'regions': ('breast', 'nipple'),
                   'role': 'shape',
                   'side': 'L',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip01_R': {'parent': 'cf_d_bnip01_R',
                   'regions': ('breast', 'nipple'),
                   'role': 'shape',
                   'side': 'R',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip025_L': {'parent': 'cf_j_bnip02root_L',
                    'regions': ('breast', 'nipple'),
                    'role': 'shape',
                    'side': 'L',
                    'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip025_R': {'parent': 'cf_j_bnip02root_R',
                    'regions': ('breast', 'nipple'),
                    'role': 'shape',
                    'side': 'R',
                    'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip02_L': {'parent': 'cf_j_bnip02root_L',
                   'regions': ('breast', 'nipple'),
                   'role': 'shape',
                   'side': 'L',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bnip02_R': {'parent': 'cf_j_bnip02root_R',
                   'regions': ('breast', 'nipple'),
                   'role': 'shape',
                   'side': 'R',
                   'tags': ('nipple_detail', 'transfer_safe_torso')},
 'cf_s_bust00_L': {'parent': 'cf_d_bust00',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust00_R': {'parent': 'cf_d_bust00',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust01_L': {'parent': 'cf_j_bust01_L',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust01_R': {'parent': 'cf_j_bust01_R',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust02_L': {'parent': 'cf_j_bust02_L',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust02_R': {'parent': 'cf_j_bust02_R',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust03_L': {'parent': 'cf_j_bust03_L',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'L',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_bust03_R': {'parent': 'cf_j_bust03_R',
                   'regions': ('breast',),
                   'role': 'shape',
                   'side': 'R',
                   'tags': ('bust_chain', 'transfer_safe_torso')},
 'cf_s_elbo_L': {'parent': 'cf_j_forearm01_L',
                 'regions': ('arm',),
                 'role': 'shape',
                 'side': 'L',
                 'tags': ('transfer_safe_arm',)},
 'cf_s_elbo_R': {'parent': 'cf_j_forearm01_R',
                 'regions': ('arm',),
                 'role': 'shape',
                 'side': 'R',
                 'tags': ('transfer_safe_arm',)},
 'cf_s_elboback_L': {'parent': 'cf_s_forearm01_L',
                     'regions': ('arm',),
                     'role': 'shape',
                     'side': 'L',
                     'tags': ('transfer_safe_arm',)},
 'cf_s_elboback_R': {'parent': 'cf_s_forearm01_R',
                     'regions': ('arm',),
                     'role': 'shape',
                     'side': 'R',
                     'tags': ('transfer_safe_arm',)},
 'cf_s_forearm01_L': {'parent': 'cf_j_forearm01_L',
                      'regions': ('arm',),
                      'role': 'shape',
                      'side': 'L',
                      'tags': ('transfer_safe_arm',)},
 'cf_s_forearm01_R': {'parent': 'cf_j_forearm01_R',
                      'regions': ('arm',),
                      'role': 'shape',
                      'side': 'R',
                      'tags': ('transfer_safe_arm',)},
 'cf_s_forearm02_L': {'parent': 'cf_d_forearm02_L',
                      'regions': ('arm',),
                      'role': 'shape',
                      'side': 'L',
                      'tags': ('transfer_safe_arm',)},
 'cf_s_forearm02_R': {'parent': 'cf_d_forearm02_R',
                      'regions': ('arm',),
                      'role': 'shape',
                      'side': 'R',
                      'tags': ('transfer_safe_arm',)},
 'cf_s_hand_L': {'parent': 'cf_j_hand_L',
                 'regions': ('hand',),
                 'role': 'shape',
                 'side': 'L',
                 'tags': ('transfer_safe_arm',)},
 'cf_s_hand_R': {'parent': 'cf_j_hand_R',
                 'regions': ('hand',),
                 'role': 'shape',
                 'side': 'R',
                 'tags': ('transfer_safe_arm',)},
 'cf_s_head': {'parent': 'cf_j_head',
               'regions': ('torso',),
               'role': 'shape',
               'side': None,
               'tags': ('transfer_safe_torso',)},
 'cf_s_kneeB_L': {'parent': 'cf_s_leg01_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_kneeB_R': {'parent': 'cf_s_leg01_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg01_L': {'parent': 'cf_j_leg01_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg01_R': {'parent': 'cf_j_leg01_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg02_L': {'parent': 'cf_d_leg02_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg02_R': {'parent': 'cf_d_leg02_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg03_L': {'parent': 'cf_d_leg03_L',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg03_R': {'parent': 'cf_d_leg03_R',
                  'regions': ('leg', 'lower_body'),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg_L': {'parent': 'cf_s_waist02',
                'regions': ('leg', 'lower_body'),
                'role': 'shape',
                'side': 'L',
                'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_leg_R': {'parent': 'cf_s_waist02',
                'regions': ('leg', 'lower_body'),
                'role': 'shape',
                'side': 'R',
                'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_neck': {'parent': 'cf_j_neck',
               'regions': ('torso',),
               'role': 'shape',
               'side': None,
               'tags': ('transfer_safe_torso',)},
 'cf_s_shoulder02_L': {'parent': 'cf_d_shoulder02_L',
                       'regions': ('arm',),
                       'role': 'shape',
                       'side': 'L',
                       'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_s_shoulder02_R': {'parent': 'cf_d_shoulder02_R',
                       'regions': ('arm',),
                       'role': 'shape',
                       'side': 'R',
                       'tags': ('transfer_safe_arm', 'transfer_safe_torso')},
 'cf_s_siri_L': {'parent': 'cf_j_siri_L',
                 'regions': ('butt', 'lower_body'),
                 'role': 'shape',
                 'side': 'L',
                 'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_s_siri_R': {'parent': 'cf_j_siri_R',
                 'regions': ('butt', 'lower_body'),
                 'role': 'shape',
                 'side': 'R',
                 'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_s_spine01': {'parent': 'cf_j_spine01',
                  'regions': ('torso',),
                  'role': 'shape',
                  'side': None,
                  'tags': ('transfer_safe_torso',)},
 'cf_s_spine02': {'parent': 'cf_j_spine02',
                  'regions': ('torso',),
                  'role': 'shape',
                  'side': None,
                  'tags': ('transfer_safe_torso',)},
 'cf_s_spine03': {'parent': 'cf_j_spine03',
                  'regions': ('torso',),
                  'role': 'shape',
                  'side': None,
                  'tags': ('transfer_safe_torso',)},
 'cf_s_thigh01_L': {'parent': 'cf_d_thigh01_L',
                    'regions': ('leg', 'lower_body'),
                    'role': 'shape',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_thigh01_R': {'parent': 'cf_d_thigh01_R',
                    'regions': ('leg', 'lower_body'),
                    'role': 'shape',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_thigh02_L': {'parent': 'cf_d_thigh02_L',
                    'regions': ('leg', 'lower_body'),
                    'role': 'shape',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_thigh02_R': {'parent': 'cf_d_thigh02_R',
                    'regions': ('leg', 'lower_body'),
                    'role': 'shape',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_thigh03_L': {'parent': 'cf_d_thigh03_L',
                    'regions': ('leg', 'lower_body'),
                    'role': 'shape',
                    'side': 'L',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_thigh03_R': {'parent': 'cf_d_thigh03_R',
                    'regions': ('leg', 'lower_body'),
                    'role': 'shape',
                    'side': 'R',
                    'tags': ('lower_body_limb', 'lower_body_with_siri', 'transfer_safe_leg')},
 'cf_s_waist01': {'parent': 'cf_j_waist01',
                  'regions': ('lower_body', 'torso'),
                  'role': 'shape',
                  'side': None,
                  'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_s_waist02': {'parent': 'cf_j_waist02',
                  'regions': ('lower_body', 'torso'),
                  'role': 'shape',
                  'side': None,
                  'tags': ('lower_body_with_siri', 'transfer_safe_leg', 'transfer_safe_torso')},
 'cf_s_wrist_L': {'parent': 'cf_d_wrist_L',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'L',
                  'tags': ('transfer_safe_arm',)},
 'cf_s_wrist_R': {'parent': 'cf_d_wrist_R',
                  'regions': ('arm',),
                  'role': 'shape',
                  'side': 'R',
                  'tags': ('transfer_safe_arm',)},
 'n_body': {'parent': 'cf_o_root', 'regions': ('root',), 'role': 'anchor', 'side': None, 'tags': ('root_anchor',)},
 'o_body_a': {'parent': 'n_body', 'regions': ('root',), 'role': 'anchor', 'side': None, 'tags': ('root_anchor',)},
 'p_cf_body_00': {'parent': None, 'regions': ('root',), 'role': 'anchor', 'side': None, 'tags': ('root_anchor',)}}


def _make_rule(name, data):
    return BoneRule(
        name=name,
        role=data["role"],
        regions=frozenset(data["regions"]),
        side=data["side"],
        parent=data["parent"],
        tags=frozenset(data["tags"]),
    )


KK_STANDARD_BODY_BONES = {name: _make_rule(name, data) for name, data in _BONE_RULE_DATA.items()}
KK_STANDARD_BODY_BONE_NAMES = frozenset(KK_STANDARD_BODY_BONES)
KK_STANDARD_BONE_PARENTS = {name: rule.parent for name, rule in KK_STANDARD_BODY_BONES.items()}

KK_BONES_BY_ROLE = {
    role: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if rule.role == role)
    for role in (ROLE_MOTION, ROLE_SHAPE, ROLE_ASSIST, ROLE_ANCHOR, ROLE_OTHER)
}

KK_BONES_BY_REGION = {
    region: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if region in rule.regions)
    for region in (
        REGION_TORSO,
        REGION_ARM,
        REGION_LEG,
        REGION_BREAST,
        REGION_HAND,
        REGION_LOWER_BODY,
        REGION_BUTT,
        REGION_NIPPLE,
        REGION_ROOT,
    )
}

KK_SPECIAL_GROUPS = {
    TAG_LOWER_BODY_LIMB: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_LOWER_BODY_LIMB in rule.tags),
    TAG_LOWER_BODY_WITH_SIRI: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_LOWER_BODY_WITH_SIRI in rule.tags),
    TAG_NIPPLE_DETAIL: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_NIPPLE_DETAIL in rule.tags),
    TAG_BUST_CHAIN: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_BUST_CHAIN in rule.tags),
    TAG_TRANSFER_SAFE_TORSO: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_TRANSFER_SAFE_TORSO in rule.tags),
    TAG_TRANSFER_SAFE_ARM: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_TRANSFER_SAFE_ARM in rule.tags),
    TAG_TRANSFER_SAFE_LEG: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_TRANSFER_SAFE_LEG in rule.tags),
    TAG_ROOT_ANCHOR: frozenset(name for name, rule in KK_STANDARD_BODY_BONES.items() if TAG_ROOT_ANCHOR in rule.tags),
}


def is_kk_standard_body_bone(name):
    return name in KK_STANDARD_BODY_BONES


def is_kk_motion_bone(name):
    rule = KK_STANDARD_BODY_BONES.get(name)
    return rule is not None and rule.role == ROLE_MOTION


def is_kk_shape_bone(name):
    rule = KK_STANDARD_BODY_BONES.get(name)
    return rule is not None and rule.role == ROLE_SHAPE


def is_kk_assist_bone(name):
    rule = KK_STANDARD_BODY_BONES.get(name)
    return rule is not None and rule.role == ROLE_ASSIST


def is_kk_anchor_bone(name):
    rule = KK_STANDARD_BODY_BONES.get(name)
    return rule is not None and rule.role == ROLE_ANCHOR


def bone_regions(name):
    rule = KK_STANDARD_BODY_BONES.get(name)
    return rule.regions if rule else frozenset()


def bone_tags(name):
    rule = KK_STANDARD_BODY_BONES.get(name)
    return rule.tags if rule else frozenset()


def is_region_bone(name, region):
    return region in bone_regions(name)


def has_bone_tag(name, tag):
    return tag in bone_tags(name)


def is_lower_body_limb_bone(name):
    return has_bone_tag(name, TAG_LOWER_BODY_LIMB)


def is_lower_body_bone(name, include_siri=True):
    tag = TAG_LOWER_BODY_WITH_SIRI if include_siri else TAG_LOWER_BODY_LIMB
    return has_bone_tag(name, tag)


def is_breast_bone(name):
    return is_region_bone(name, REGION_BREAST)


def is_nipple_detail_bone(name):
    return has_bone_tag(name, TAG_NIPPLE_DETAIL)


def is_bust_chain_bone(name):
    return has_bone_tag(name, TAG_BUST_CHAIN)


def is_transfer_region_bone(name, region):
    if region == TRANSFER_REGION_ARM:
        return has_bone_tag(name, TAG_TRANSFER_SAFE_ARM)
    if region == TRANSFER_REGION_LEG:
        return has_bone_tag(name, TAG_TRANSFER_SAFE_LEG)
    return has_bone_tag(name, TAG_TRANSFER_SAFE_TORSO)


def is_body_weight_group(name, source_body_group_names=None):
    if source_body_group_names is not None:
        return name in source_body_group_names
    return is_kk_standard_body_bone(name)


def is_clothing_dynamic_group(name, source_body_group_names, replaceable_vrc_groups=None):
    if is_body_weight_group(name, source_body_group_names):
        return False
    if replaceable_vrc_groups and name in replaceable_vrc_groups:
        return False
    return True


def filter_groups_for_region(group_names, region, source_body_group_names=None):
    return {
        name
        for name in group_names
        if is_body_weight_group(name, source_body_group_names) and is_transfer_region_bone(name, region)
    }


def irrelevant_groups_for_region(group_names, region, source_body_group_names=None):
    return {
        name
        for name in group_names
        if is_body_weight_group(name, source_body_group_names) and not is_transfer_region_bone(name, region)
    }
